# Generated by Django 4.2.7 on 2023-11-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
