# Generated by Django 4.2.7 on 2023-12-10 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_bloodgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonar',
            fields=[
                ('uid', models.URLField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('units', models.PositiveIntegerField()),
                ('body_weight', models.CharField(help_text='Weight in KG', max_length=100)),
                ('accepted', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=200)),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bloodgroup')),
                ('donar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
