# Generated by Django 4.2.7 on 2023-12-10 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_blooddonar_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequests',
            name='blood_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bloodgroup', to_field='group'),
        ),
    ]
