# Generated by Django 4.2.7 on 2023-12-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_bloodrequests_blood_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blooddonar',
            old_name='description',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='blooddonar',
            name='body_weight',
        ),
        migrations.AddField(
            model_name='blooddonar',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
