# Generated by Django 4.2.7 on 2024-01-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_description_blooddonar_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequests',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
