# Generated by Django 4.2.7 on 2024-01-04 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_bloodinventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodinventory',
            name='blood_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bloodgroup', to_field='group', unique=True),
        ),
    ]
