# Generated by Django 4.2.7 on 2024-01-04 15:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_bloodinventory_blood_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blooddonar',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='bloodrequests',
            name='accepted',
        ),
        migrations.AlterField(
            model_name='blooddonar',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BloodInventory',
        ),
    ]
